# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-08-15 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.baseInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awardinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.baseInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.baseInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='familymember',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.baseInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mingerelation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.baseInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='positionsincepast',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.baseInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='punish',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.baseInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.baseInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.baseInfo'),
            preserve_default=False,
        ),
    ]
